### ISSUE TITLE
Payment Module

### ISSUE THREAD

**Issue by arnab77in** [nopadvance/NopCommerce-Flutter-Mobile-Application#1]
How do you integrate a payment module like RazorPay, CCavenue etc. into mobile App and API

**Comment by SagarKayastha** [comment]
Hello @arnab77in ,

For mobile app please see => validatePaymentInfo() method in https://github.com/nopadvance/NopCommerce-Flutter-Mobile-Application/blob/main/lib/Services/CheckoutService.dart file.

For API please see => ValidatePaymentInfoAsync() and ConfirmOrderAsync methods in \Controllers\Public\PublicCheckoutController.cs file.

If you want to integrate any new payment then you will have to add them by changing in the api source code in the above mentioned methods.
Please let me know if this doesn't answers your question.

**Comment by arnab77in** [comment]
Hi Sagar,

Would you people able to do it as a project if require?

Thanks

**Comment by atulrungta** [comment]
@arnab77in sure, you can send an email with your requirements to us on sales@nopadvance.com
