### ISSUE TITLE
There is no checkout button available after running code.

### ISSUE THREAD

**Issue by tusharuit25** [nopadvance/NopCommerce-Flutter-Mobile-Application#4]
![simulator_screenshot_65717461-5DB5-449E-B8D9-9335E020A773](https://user-images.githubusercontent.com/5900498/218149181-ad4c347f-dcd3-47b5-8aa4-f13154cad525.png)

**Comment by atulrungta** [comment]
@tusharuit25 it must be available at the end of that page if you pull it up.
See attached image from our demo application on apple app store.
![image](https://user-images.githubusercontent.com/7768934/218265486-a8c7f25a-f0b0-4caf-8618-4d87ae0841de.jpeg)
