### ISSUE TITLE
Is there specific setting that I am missing so that I am not getting that button?

### ISSUE THREAD

**Issue by tusharuit25** [nopadvance/NopCommerce-Flutter-Mobile-Application#5]
<img width="1440" alt="Screenshot 2023-02-11 at 8 48 56 PM" src="https://user-images.githubusercontent.com/5900498/218266482-eb74462e-4a35-48e4-851b-e9781b90a1de.png">

**Comment by atulrungta** [comment]
@tusharuit25 is checkout enabled in your nopCommerce?

**Comment by tusharuit25** [comment]
Yes I do there issue with this flutter version which latest right now its not comparing String Object with null
I debug the application and change line like below and it started working now I can see checkout Button
`homeProvider.getCartModel.minOrderSubtotalWarning == null && !homeProvider.getCartModel.hideCheckoutButton ?`
to
'homeProvider.getCartModel.minOrderSubtotalWarning == "" && !homeProvider.getCartModel.hideCheckoutButton ? 
in `ShoppingCartContentComponent.dart` file and all data models object receiving the data from API has same null exceptions see screenshot attached with change 
<img width="1440" alt="Screenshot 2023-02-11 at 9 16 57 PM" src="https://user-images.githubusercontent.com/5900498/218267496-123bba87-5f64-4e5c-b5b3-ec6e4489eef0.png">

**Comment by atulrungta** [comment]
@tusharuit25 that's good news. Thank you so much for figuring this out.
